default['jboss']['owner'] = "jboss"
default['jboss']['group'] = "jboss"
default['jboss']['install_directory'] = "/usr/local"
default['jboss']['sourceFile'] = "jboss-6.0.0.Final"
default['jboss']['sourceURL'] = "http://11.120.101.55/REPO/jboss-as-distribution-6.0.0.Final.zip"
default['jboss']['jboss_home'] = "/usr/local/jboss"
default['jboss']['java_home'] = "/usr/bin"
default['jboss']['init'] = "jboss_init_ubuntu.sh"
default['jboss']['bindings'] = "bindings-jboss-beans.xml"
default['jboss']['default_bindings'] = "default/conf/bindingservice.beans/META-INF/bindings-jboss-beans.xml"

default['jboss']['gid'] = "880"
default['jboss']['homedir'] = "/usr/local"
default['jboss']['shell'] = "/bin/false"
default['jboss']['uid'] = "5174"
default['jboss']['skeldir'] = " /etc/skel"
default['jboss']['comment'] = "Jboss ID"
